# default_platform(:ios)
# platform :ios do
#   desc "Upload IPA to TestFlight"
#   lane :upload_ipa_to_testflight do
#     api_key = app_store_connect_api_key(
#       key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
#       issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
#       key_content: ENV['APP_STORE_CONNECT_API_KEY']
#     )

#      pilot(
#        api_key: api_key,
#        ipa: ENV['RUNNER_TEMP'] + "/list-for-ios.ipa",
#        app_identifier: "com.pizza.man" # Ensure this matches exactly
#      )
#    end
#  end


# fastlane/Fastfile
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: File.read('fastlane/AuthKey.p8')
    )

    upload_to_testflight(
      ipa: options[:ipa],
      api_key: api_key
    )
  end
end
