# fastlane/Fastfile
platform :ios do
  desc "Upload IPA to TestFlight"
  lane :upload_ipa_to_testflight do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY']
    )

    # build_app(
    #   project: "Pizza Man.xcodeproj", # Use this for .xcodeproj
    #   scheme: "Pizza Man"
    # )

    upload_to_testflight(
      ipa: options[:ipa],
      api_key: api_key,
      app_identifier: "com.pizza.man" # Ensure this matches exactly
    )
  end
end
